### ISSUE TITLE
Heroku build number

### ISSUE THREAD

**Issue by JamieDixon** [mars/create-react-app-inner-buildpack#6]
Hi there,

Thanks for creating this build pack. Really appreciate the effort and would be stuck without it.

I'm wondering if there's some way of using this to expose the Heroku deployment number to our React app? Is it held in an environment var or as part of the build artefacts?

**Comment by faheemmughal** [comment]
I was facing the same issue. My solution was to create a buildpack that would translate whitelisted  `HEROKU_*` environment variables to `REACT_APP_HEROKU_*` variables. And made sure to add that buildpack before this one.

If it helps, here is my take: https://github.com/faheemmughal/react-app-heroku-environment-buildpack

**Comment by mars** [comment]
Thanks for the answer @faheemmughal,

See the main buildpack docs for a `REACT_APP_` name spacing technique that does not require a separate buildpack: [how-to use Add-on config vars](https://github.com/mars/create-react-app-buildpack#user-content-add-on-config-vars) shows how to use a `.profile.d/` file to alias the config vars at runtime.
