### ISSUE TITLE
Determine js_bundle path from static.json, if present

### ISSUE THREAD

**Issue by jared-dykstra** [mars/create-react-app-inner-buildpack#7]
The js_bundle path is [currently hardcoded](https://github.com/mars/create-react-app-inner-buildpack/blob/master/.profile.d/inject_react_app_env.sh#L10):
```sh
js_bundle=/app/build/static/js/main.*.js
```
However, the outer buildpack [may set a different root via `static.json`](https://github.com/mars/create-react-app-buildpack#web-server), which causes the js_bundle to be produced at a different path.

The js_bundle path should be derived from the content of `/app/static.json`'s `root` if present and retain the current behavior if not.
```sh
js_bundle=/app/${static.json.root}/build/static/js/main.*.js
```

Without this change, the following error results at runtime from sites deployed to Heroku, as the `REACT_APP_VARS_AS_JSON` token is not replaced.
```
Runtime env vars cannot be parsed. Content is `{{REACT_APP_VARS_AS_JSON_______…`
```

**Comment by mars** [comment]
Hi @jared-dykstra. Thank you for opening this pull request. Coincidentally, I am generalizing this JS Runtime Env pattern, experimenting with a version for use by any bundled JS app:
https://github.com/mars/heroku-js-runtime-env-buildpack

With this generalized technique, it’s always necessary to specify the bundle’s location through config var `JS_RUNTIME_TARGET_BUNDLE`

Following the results of this generalized JS Runtime Env, create-react-app-buildpack (the parent of this repo) may migrate to use that solution.

This PR elegantly solves the part of the same problem through introspection of `static.json`, but remains specific to create-react-app & the static site buildpack. 
Also requires some time to consider how this might break things for other edge cases. I believe some folks may be moving files around after this buildpack builds the bundle. Would this break their build?

Thanks again for this 🙇‍♂️🙏 Great to see how other folks are using create-react-app-buildpack.

**Comment by jared-dykstra** [comment]
Thanks, @mars .

You're welcome to do with PR #8 as you wish, especially as a change to the outer bundle is required to use this change.

Unfortunately, I do not know enough to answer your question about whether or not this would break their build.  It seems likely that the worst-case is `REACT_APP_VARS_AS_JSON` token isn't replaced and it fails the same way it would without my change.

For now, I'm using my forks:
https://github.com/jared-dykstra/create-react-app-buildpack
https://github.com/jared-dykstra/create-react-app-inner-buildpack

**Comment by weyert** [comment]
Ah yes, this might fix the issue when you use vendor spitting with CRA. Just got bitten by this today. The problem when do that it won't be able to find the file as main.*.js doesn't exist and then just `ls` just exists which causes the following:

```
Injecting runtime env into app
       bin
       boot
       build
       cache
       dev
       etc
       exec
       home
       lib
       lib64
       media
       mnt
       opt
       proc
       root
       run
       sbin
       srv
       start
       sys
       tmp
       usr
       var (from .profile.d/inject_react_app_env.sh)
       /app/.heroku/create-react-app/injectable_env.rb:27:in `read': No such file or directory @ rb_sysopen - app (Errno::ENOENT)
```

**Comment by mars** [comment]
I'm considering adding a simple `JS_RUNTIME_TARGET_BUNDLE` env var to support overriding of the default bundle location.

This would support setting a special bundle location for the two situations mentioned so far:

1. default bundle in a customized **static.json** `root`
2. split bundle for the bundle containing **@mars/heroku-js-runtime-env** module

I don't see another graceful way to handle all the cases where the bundle is not at the expected location. Any other ideas?

**Comment by mars** [comment]
I've added support for custom bundle location as a feature branch. Try it out with this buildpack branch setting:

```bash
heroku buildpacks:set https://github.com/mars/create-react-app-buildpack.git#custom-bundle-path
```

Then, set `JS_RUNTIME_TARGET_BUNDLE` to the bundle location.

See the branch's README [custom bundle location](https://github.com/mars/create-react-app-buildpack/blob/custom-bundle-path/README.md#user-content-custom-bundle-location) for more detail on how to use it.

**Comment by weyert** [comment]
Thank you @mars. I will give it a try. Currently in the middle of going into production

**Comment by mars** [comment]
Support for [custom bundle location](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-custom-bundle-location) with `JS_RUNTIME_TARGET_BUNDLE` is now part of the buildpack.
